// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function querySelector(str) {
  return Caml_option.nullable_to_opt(document.querySelector(str));
}

function getContext(elem, str) {
  return Caml_option.nullable_to_opt(elem.getContext(str));
}

export {
  querySelector ,
  getContext ,
}
/* No side effect */
