# Generated by rebar3_nix
let fetchOnly = { src, ... }: src;
in { builder ? fetchOnly, fetchHex, fetchgit, fetchFromGitHub, overrides ? (x: y: { }) }:
let
  self = packages // (overrides self packages);
  packages = with self; {
    ranch = builder {
      name = "ranch";
      version = "git";
      src = fetchFromGitHub {
        owner = "ninenines";
        repo = "ranch";
        rev = "10b51304b26062e0dbfd5e74824324e9a911e269";
        sha256 = "1fx7pnpq7sg9l9n6wlly1v2sikq1y7sxci318ciidbq8g0pv3mfm";
      };
      beamDeps = [ ];
    };
    cowlib = builder {
      name = "cowlib";
      version = "git";
      src = fetchFromGitHub {
        owner = "ninenines";
        repo = "cowlib";
        rev = "d0ab49ed797e5bb48209825428d26947d74aabd5";
        sha256 = "0b22c2dy3gpnq53l0w1k8mjf1dr0gpbd36fwv7a6kfzd5lsgdpaw";
      };
      beamDeps = [ ];
    };
    color = builder {
      name = "color";
      version = "1.0.0";
      src = fetchHex {
        pkg = "erlang_color";
        version = "1.0.0";
        sha256 = "sha256-axfl5YnI/vVAV0yeoytnzsLIpEKDqv5HTW5YGPs+4Dg=";
      };
      beamDeps = [ ];
    };
    ltest = builder {
      name = "ltest";
      version = "0.13.11";
      src = fetchHex {
        pkg = "ltest";
        version = "0.13.11";
        sha256 = "sha256-T2Jx6F/H/lxER9FTjKKNWtI/IB/ZFe4FPDfJJ+tB2tU=";
      };
      beamDeps = [ color lfe ];
    };
    lfe = builder {
      name = "lfe";
      version = "2.2.0";
      src = fetchHex {
        pkg = "lfe";
        version = "2.2.0";
        sha256 = "sha256-wJIjzAvz7BILeRNx9qo/EM1aHR/utD+wiz9KMdZxd0k=";
      };
      beamDeps = [ ];
    };
    cowboy = builder {
      name = "cowboy";
      version = "git";
      src = fetchFromGitHub {
        owner = "ninenines";
        repo = "cowboy";
        rev = "24d32de931a0c985ff7939077463fc8be939f0e9";
        sha256 = "01h8523q2v41wnczmx68wi2a4akjx3v6lbsdqhdibgzz8cs16zlz";
      };
      beamDeps = [ cowlib ranch ];
    };
  };
in self
