# Generated by rebar3_nix
let fetchOnly = { src, ... }: src;
in { builder ? fetchOnly, fetchHex, fetchgit, fetchFromGitHub, overrides ? (x: y: { }) }:
let
  self = packages // (overrides self packages);
  packages = with self; {
    ranch = builder {
      name = "ranch";
      version = "1.8.0";
      src = fetchHex {
        pkg = "ranch";
        version = "1.8.0";
        sha256 = "sha256-SfvP02gvqx9dEJNRthJXZ22hov2+KVkEF21eUhot3+U=";
      };
      beamDeps = [ ];
    };
    cowlib = builder {
      name = "cowlib";
      version = "2.13.0";
      src = fetchHex {
        pkg = "cowlib";
        version = "2.13.0";
        sha256 = "sha256-4eEoTcP8Awpksa0Ng4KufpnaRsMka4FTGKS4SIc4AKQ=";
      };
      beamDeps = [ ];
    };
    color = builder {
      name = "color";
      version = "1.0.0";
      src = fetchHex {
        pkg = "erlang_color";
        version = "1.0.0";
        sha256 = "sha256-axfl5YnI/vVAV0yeoytnzsLIpEKDqv5HTW5YGPs+4Dg=";
      };
      beamDeps = [ ];
    };
    ltest = builder {
      name = "ltest";
      version = "0.13.11";
      src = fetchHex {
        pkg = "ltest";
        version = "0.13.11";
        sha256 = "sha256-T2Jx6F/H/lxER9FTjKKNWtI/IB/ZFe4FPDfJJ+tB2tU=";
      };
      beamDeps = [ color lfe ];
    };
    lfe = builder {
      name = "lfe";
      version = "2.2.0";
      src = fetchHex {
        pkg = "lfe";
        version = "2.2.0";
        sha256 = "sha256-wJIjzAvz7BILeRNx9qo/EM1aHR/utD+wiz9KMdZxd0k=";
      };
      beamDeps = [ ];
    };
    cowboy = builder {
      name = "cowboy";
      version = "2.12.0";
      src = fetchHex {
        pkg = "cowboy";
        version = "2.12.0";
        sha256 = "sha256-inq+bRgzcs6yHKonCb7JKKsrcuGKORGqF3Fjm++CZR4=";
      };
      beamDeps = [ cowlib ranch ];
    };
  };
in self
